import Head from 'next/head'
import React, { useState } from 'react';

export default function Home() {
  const [input, setInput] = useState('')
  const [response, setResponse] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true)
    try {
      const res = await fetch('/api/tellGPT', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: input }),
      });
      const data = await res.json();
      setResponse(data.response);
      setIsLoading(false)
      document.body.style.background = `rgb(${Math.random()*255},${Math.random()*255},${Math.random()*255})`
    } catch (error) {
      console.error('Error:', error);
      setResponse('An error occurred.');
    }
  }

  return (
<>
      <Head>
        <title>ChatGPT API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Enter your message"
          />
          <button type="submit">Send</button>
        </form>
        <div>
          {isLoading ? <p>Waiting...</p> : <p>{response}</p>}
        </div>
      </main>
    </>
  )
}
